KERNELDIR := /lib/modules/$(shell uname -r)/build
CURRENT_KERNEL_VERSION := $(shell uname -r)
KERNEL_VERSION_5_10_VM := $(CURRENT_KERNEL_VERSION)-vm
KERNEL_VERSION_5_10 := $(CURRENT_KERNEL_VERSION)

ifeq ($(PLATFORM),$(KERNEL_VERSION_5_10_VM))
EXTRA_CFLAGS += -DLINUX_5_10_VM
endif
ifeq ($(PLATFORM),$(KERNEL_VERSION_5_10))
EXTRA_CFLAGS += -DLINUX_5_10
endif

EXTRA_CFLAGS += -DDEBUG
# EXTRA_CFLAGS += -DXT_ENABLE_CDEV
# EXTRA_CFLAGS += -DXT_RDMA_ENABLE
ccflags-y := -I $(PWD)/inc
EXTRA_CFLAGS += -g

